update scripts for archiving and testing

diff --git a/auto-archive b/auto-archive
--- a/auto-archive
+++ b/auto-archive
@@ -13,52 +13,19 @@ print_help() {
     echo -e "  4 - Concurrency Control"
 }
 
-min_proj=0
-max_proj=4
-
-if [[ $# -ne 1 || $1 -lt min_proj || $1 -gt max_proj ]]; then
-    print_help
-    exit 0
-fi
-
 out="proj$1-submission"
-
 if [[ -f ./$out.zip ]]; then
     rm $out.zip
 fi
 
-echo "Start packing $out.zip..."
-if [[ $1 -eq 0 ]]; then
-    zip $out -r src/include/primer/p0_starter.h
-fi
-
-if [[ $1 -ge 1 ]]; then
-    echo "zip project 1..."
-    zip $out -r \
-    src/include/buffer/lru_replacer.h \
-    src/buffer/lru_replacer.cpp \
-    src/include/buffer/buffer_pool_manager.h \
-    src/buffer/buffer_pool_manager.cpp
-fi
-
-if [[ $1 -ge 2 ]]; then
-    echo "zip project 2..."
-    zip $out -ur \
-    src/include/storage/page/b_plus_tree_page.h \
-    src/storage/page/b_plus_tree_page.cpp \
-    src/include/storage/page/b_plus_tree_internal_page.h \
-    src/storage/page/b_plus_tree_internal_page.cpp \
-    src/include/storage/page/b_plus_tree_leaf_page.h \
-    src/storage/page/b_plus_tree_leaf_page.cpp \
-    src/include/storage/index/b_plus_tree.h \
-    src/storage/index/b_plus_tree.cpp \
-    src/include/storage/index/index_iterator.h \
-    src/storage/index/index_iterator.cpp
-fi
-
-if [[ $1 -ge 3 ]]; then
-    echo "zip project 3..."
-    zip $out -ur \
+case $1 in
+  4)
+    zip $out -urq \
+    src/concurrency/lock_manager.cpp \
+    src/include/concurrency/lock_manager.h
+  ;&
+  3)
+    zip $out -urq \
     src/include/catalog/catalog.h \
     src/include/execution/execution_engine.h \
     src/include/execution/executor_factory.h \
@@ -84,12 +51,35 @@ if [[ $1 -ge 3 ]]; then
     src/execution/limit_executor.cpp \
     src/execution/aggregation_executor.cpp \
     src/storage/index/b_plus_tree_index.cpp
-fi
-
-if [[ $1 -ge 4 ]]; then
-    echo "zip project 4..."
-    zip $out -ur \
-    src/concurrency/lock_manager.cpp \
-    src/include/concurrency/lock_manager.h
-fi
+  ;&
+  2)
+    zip $out -urq \
+    src/include/storage/page/b_plus_tree_page.h \
+    src/storage/page/b_plus_tree_page.cpp \
+    src/include/storage/page/b_plus_tree_internal_page.h \
+    src/storage/page/b_plus_tree_internal_page.cpp \
+    src/include/storage/page/b_plus_tree_leaf_page.h \
+    src/storage/page/b_plus_tree_leaf_page.cpp \
+    src/include/storage/index/b_plus_tree.h \
+    src/storage/index/b_plus_tree.cpp \
+    src/include/storage/index/index_iterator.h \
+    src/storage/index/index_iterator.cpp
+  ;&
+  1)
+    zip $out -urq \
+    src/include/buffer/lru_replacer.h \
+    src/buffer/lru_replacer.cpp \
+    src/include/buffer/buffer_pool_manager.h \
+    src/buffer/buffer_pool_manager.cpp
+  ;;
+  0)
+    zip $out -urq src/include/primer/p0_starter.h
+  ;;
+  *)
+    echo "Invalid input: $1"
+    print_help
+    exit 1
+  ;;
+esac
+echo "Files has been writen into $out.zip..."
 unzip -l $out.zip
